import { PrismaClient, EntityType, PlaceCategory, RampStatus, GuidingBlockStatus, SidewalkCondition, SurfaceCondition, SeatingAvailability, ToiletAccessibility, LightingLevel, CrowdLevel, WeeklyPattern, ActivityStatus, Role } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting DifaMap Makassar database seeding...');

  // 1. Seed Contributor / Surveyor User
  const demoUser = await prisma.user.upsert({
    where: { email: 'contributor@difamap.id' },
    update: {},
    create: {
      id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
      email: 'contributor@difamap.id',
      name: 'Fiqri DifaMap Explorer',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      role: Role.SURVEYOR,
    },
  });

  console.log(`👤 Seeded User: ${demoUser.name} (${demoUser.email})`);

  // 2. Seed Makassar Locations (Places, Sidewalks, Transit Hubs)
  const locationsData = [
    {
      id: '11111111-1111-1111-1111-111111111111',
      name: 'Mal Ratu Indah (MaRI)',
      entityType: EntityType.PLACE,
      category: PlaceCategory.MALL,
      specificLocation: 'Jl. Dr. Sam Ratulangi No.35, Mamajang, Makassar',
      description: 'Pusat perbelanjaan ramah disabilitas dan lansia dengan fasilitas ramp standar internasional di pintu masuk utama dan utara.',
      coverImageUrl: 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=800',
      latitude: -5.15832,
      longitude: 119.41654,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.GOOD,
      sidewalkCondition: SidewalkCondition.NOT_APPLICABLE,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.AVAILABLE_GOOD,
      lightingLevel: LightingLevel.BRIGHT,
      crowdLevel: CrowdLevel.CROWDED,
      peakHours: '16:00 - 20:30',
      safeVisitTime: '10:00 - 15:30',
      weeklyPattern: WeeklyPattern.WEEKEND_BUSY,
      overallScore: 4.8,
      physicalScore: 4.9,
      safetyScore: 4.7,
      aiSummary: 'Mall dengan aksesibilitas ramah kursi roda yang sangat baik. Dilengkapi ramp di seluruh pintu masuk, lift dengan tombol braille bersuara, dan toilet khusus disabilitas yang bersih.',
      aiInsights: {
        strengths: ['Ramp landai < 8% dengan pegangan tangan', 'Toilet disabilitas di setiap lantai', 'Jalur drop-off kursi roda langsung'],
        barriers: ['Keramaian tinggi di akhir pekan membutuhkan kehati-hatian pengguna kursi roda'],
        keyPoints: ['Aksesibel Kursi Roda', 'Guiding Block Tersambung', 'Lift Braille'],
      },
      economicScore: 88.5,
      priorityIndex: 32.0,
    },
    {
      id: '22222222-2222-2222-2222-222222222222',
      name: 'Nipah Park Makassar',
      entityType: EntityType.PLACE,
      category: PlaceCategory.MALL,
      specificLocation: 'Jl. Urip Sumoharjo No.23, Panaikang, Panakkukang, Makassar',
      description: 'Green lifestyle mall dengan koridor semi-outdoor lebar, lantai datar, dan jalur pedestrian yang ramah pengguna kursi roda.',
      coverImageUrl: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=800',
      latitude: -5.13781,
      longitude: 119.44892,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.GOOD,
      sidewalkCondition: SidewalkCondition.NOT_APPLICABLE,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.AVAILABLE_GOOD,
      lightingLevel: LightingLevel.BRIGHT,
      crowdLevel: CrowdLevel.MODERATE,
      peakHours: '17:00 - 21:00',
      safeVisitTime: '10:00 - 16:00',
      weeklyPattern: WeeklyPattern.BALANCED,
      overallScore: 4.9,
      physicalScore: 5.0,
      safetyScore: 4.8,
      aiSummary: 'Konsep mall hijau dengan sirkulasi udara alami dan lantai tanpa undakan. Seluruh tenant dan lantai dapat diakses mandiri oleh pengguna kursi roda.',
      aiInsights: {
        strengths: ['Koridor sangat luas (>3m)', 'Ramp kelandaian sangat landai', 'Tersedia kursi roda peminjaman gratis'],
        barriers: ['Area outdoor perlu kehati-hatian saat hujan karena lantai basah'],
        keyPoints: ['Ramah Kursi Roda Penuh', 'Taman Terbuka Aksesibel', 'Toilet Standar Nasional'],
      },
      economicScore: 92.0,
      priorityIndex: 28.5,
    },
    {
      id: '33333333-3333-3333-3333-333333333333',
      name: 'Halte Karebosi (Teman Bus Makassar)',
      entityType: EntityType.TRANSIT_HUB,
      category: PlaceCategory.BUS_STOP,
      specificLocation: 'Jl. Ahmad Yani, Depan Lapangan Karebosi, Makassar',
      description: 'Halte transit utama armada Teman Bus Trans Mamminasata Koridor 1 dan 2 dengan jalur integrasi ke pusat kota.',
      coverImageUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
      latitude: -5.13421,
      longitude: 119.40932,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.DAMAGED,
      sidewalkCondition: SidewalkCondition.GOOD,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.NOT_AVAILABLE,
      lightingLevel: LightingLevel.BRIGHT,
      crowdLevel: CrowdLevel.CROWDED,
      peakHours: '06:30 - 08:30, 16:30 - 18:30',
      safeVisitTime: '09:00 - 16:00',
      weeklyPattern: WeeklyPattern.WEEKDAY_BUSY,
      overallScore: 4.0,
      physicalScore: 3.9,
      safetyScore: 4.1,
      aiSummary: 'Halte sentral transportasi massal dengan ramp naik bus yang landai. Guiding block ubin taktil di sekitar trotoar luar sempat terputus dan butuh perbaikan sambungan rute.',
      aiInsights: {
        strengths: ['Ramp masuk halte berpegangan tangan', 'Penerangan halte terang', 'Dekat dengan penyeberangan zebra cross'],
        barriers: ['Ubin pemandu tunanetra terputus di dekat tiang rambu', 'Tidak ada toilet umum di dalam halte'],
        keyPoints: ['Transit Utama Teman Bus', 'Ramp Halte Baik', 'Prioritas Perbaikan Taktil'],
      },
      economicScore: 95.0,
      priorityIndex: 68.0,
    },
    {
      id: '44444444-4444-4444-4444-444444444444',
      name: 'Anjungan Pantai Losari',
      entityType: EntityType.PLACE,
      category: PlaceCategory.TOURISM,
      specificLocation: 'Jl. Penghibur, Losari, Ujung Pandang, Makassar',
      description: 'Kawasan wisata ruang terbuka publik pesisir ikonik Kota Makassar dengan anjungan luas yang dapat dilalui kursi roda.',
      coverImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      latitude: -5.14766,
      longitude: 119.40632,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.GOOD,
      sidewalkCondition: SidewalkCondition.GOOD,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.AVAILABLE_GOOD,
      lightingLevel: LightingLevel.BRIGHT,
      crowdLevel: CrowdLevel.CROWDED,
      peakHours: '16:30 - 20:00 (Sunset)',
      safeVisitTime: '06:00 - 17:30',
      weeklyPattern: WeeklyPattern.WEEKEND_BUSY,
      overallScore: 4.7,
      physicalScore: 4.8,
      safetyScore: 4.6,
      aiSummary: 'Destinasi wisata terbuka yang sangat nyaman untuk pengguna kursi roda dan lansia. Memiliki banyak tempat istirahat dengan pemandangan laut dan jalur tanpa undakan.',
      aiInsights: {
        strengths: ['Trotoar anjungan sangat luas dan rata', 'Ramp landai di setiap zona masuk', 'Banyak bangku istirahat'],
        barriers: ['Pusat jajanan kuliner di malam hari terkadang mempersempit jalur pedestrian'],
        keyPoints: ['Pemandangan Laut Losari', 'Ramp Ramah Kursi Roda', 'Banyak Tempat Duduk'],
      },
      economicScore: 91.0,
      priorityIndex: 35.0,
    },
    {
      id: '55555555-5555-5555-5555-555555555555',
      name: 'Trotoar Jl. Penghibur (Benteng Rotterdam - Losari)',
      entityType: EntityType.SIDEWALK,
      category: PlaceCategory.PEDESTRIAN_PATH,
      specificLocation: 'Sepanjang Jl. Penghibur, Ujung Pandang, Makassar',
      description: 'Ruas trotoar pedestrian utama kawasan heritage dan wisata pesisir barat Makassar.',
      coverImageUrl: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=800',
      latitude: -5.14125,
      longitude: 119.40582,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.GOOD,
      sidewalkCondition: SidewalkCondition.GOOD,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.NOT_AVAILABLE,
      lightingLevel: LightingLevel.BRIGHT,
      crowdLevel: CrowdLevel.MODERATE,
      peakHours: '17:00 - 20:00',
      safeVisitTime: '06:00 - 18:00',
      weeklyPattern: WeeklyPattern.BALANCED,
      overallScore: 4.5,
      physicalScore: 4.6,
      safetyScore: 4.4,
      aiSummary: 'Jalur trotoar ramah disabilitas dengan ubin pengarah guiding block kuning yang tersambung rapi, bollard pelindung dari motor, dan kelandaian rata.',
      aiInsights: {
        strengths: ['Guiding block rapi tersambung', 'Bollard pelindung trotoar', 'Lampu jalan terang di malam hari'],
        barriers: ['Beberapa penyeberangan belum memiliki tombol suara akustik (pelican crossing)'],
        keyPoints: ['Trotoar Rata & Nyaman', 'Guiding Block Tersambung', 'Penerangan Jalan Baik'],
      },
      economicScore: 84.0,
      priorityIndex: 38.0,
    },
    {
      id: '66666666-6666-6666-6666-666666666666',
      name: 'Danau UNHAS Tamalanrea',
      entityType: EntityType.PLACE,
      category: PlaceCategory.TOURISM,
      specificLocation: 'Kampus UNHAS Tamalanrea, Jl. Perintis Kemerdekaan KM 10, Makassar',
      description: 'Kawasan danau rekreasi dan ruang terbuka hijau kampus Universitas Hasanuddin.',
      coverImageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
      latitude: -5.13842,
      longitude: 119.49214,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.NONE,
      sidewalkCondition: SidewalkCondition.NOT_APPLICABLE,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.NOT_AVAILABLE,
      lightingLevel: LightingLevel.DIM,
      crowdLevel: CrowdLevel.MODERATE,
      peakHours: '06:00 - 08:00, 16:30 - 18:00',
      safeVisitTime: '06:00 - 17:30',
      weeklyPattern: WeeklyPattern.WEEKEND_BUSY,
      overallScore: 3.8,
      physicalScore: 4.0,
      safetyScore: 3.6,
      aiSummary: 'Area hijau yang sejuk dengan jalur lingkar danau datar yang mudah dilalui kursi roda. Belum memiliki guiding block khusus dan penerangan malam hari masih redup di sisi timur.',
      aiInsights: {
        strengths: ['Jalur datar bebas undakan', 'Suasana asri dan tenang', 'Banyak gazebo istirahat'],
        barriers: ['Belum ada guiding block tunanetra', 'Pencahayaan redup setelah maghrib'],
        keyPoints: ['Danau Asri Kampus', 'Jalur Datar Kursi Roda', 'Perlu Lampu Tambahan'],
      },
      economicScore: 65.0,
      priorityIndex: 52.0,
    },
    {
      id: '77777777-7777-7777-7777-777777777777',
      name: 'RSUP Dr. Wahidin Sudirohusodo',
      entityType: EntityType.PLACE,
      category: PlaceCategory.HEALTHCARE,
      specificLocation: 'Jl. Perintis Kemerdekaan KM 11, Tamalanrea, Makassar',
      description: 'Pusat rujukan kesehatan utama di Indonesia Timur dengan standar fasilitas aksesibilitas disabilitas lengkap.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800',
      latitude: -5.13455,
      longitude: 119.49520,
      rampStatus: RampStatus.GOOD,
      guidingBlockStatus: GuidingBlockStatus.GOOD,
      sidewalkCondition: SidewalkCondition.NOT_APPLICABLE,
      surfaceCondition: SurfaceCondition.SMOOTH,
      seatingAvailability: SeatingAvailability.AVAILABLE,
      toiletAccessibility: ToiletAccessibility.AVAILABLE_GOOD,
      lightingLevel: LightingLevel.BRIGHT,
      crowdLevel: CrowdLevel.MODERATE,
      peakHours: '08:00 - 13:00',
      safeVisitTime: '07:00 - 18:00',
      weeklyPattern: WeeklyPattern.WEEKDAY_BUSY,
      overallScore: 5.0,
      physicalScore: 5.0,
      safetyScore: 5.0,
      aiSummary: 'Fasilitas kesehatan dengan standar aksesibilitas paripurna. Tersedia ramp landai < 6%, tactile block lengkap dari lobby hingga poli, serta lift khusus pengguna kursi roda.',
      aiInsights: {
        strengths: ['Aksesibilitas 100% lengkap', 'Petugas bantuan siaga 24 jam', 'Toilet disabilitas standar Permen PU'],
        barriers: ['Tidak ada hambatan fisik signifikan'],
        keyPoints: ['Fasilitas Kesehatan Unggulan', 'Standar Disabilitas Lengkap', 'Ramp & Lift Khusus'],
      },
      economicScore: 89.0,
      priorityIndex: 20.0,
    },
    {
      id: '88888888-8888-8888-8888-888888888888',
      name: 'Trotoar Jl. Perintis Kemerdekaan KM 10 (Depan Pintu 1 UNHAS)',
      entityType: EntityType.SIDEWALK,
      category: PlaceCategory.PEDESTRIAN_PATH,
      specificLocation: 'Jl. Perintis Kemerdekaan KM 10, Tamalanrea, Makassar',
      description: 'Segmen trotoar koridor arteri utama di depan gerbang utama Kampus UNHAS.',
      coverImageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
      latitude: -5.13612,
      longitude: 119.48931,
      rampStatus: RampStatus.NONE,
      guidingBlockStatus: GuidingBlockStatus.DAMAGED,
      sidewalkCondition: SidewalkCondition.DAMAGED,
      surfaceCondition: SurfaceCondition.POTHOLE,
      seatingAvailability: SeatingAvailability.NOT_AVAILABLE,
      toiletAccessibility: ToiletAccessibility.NOT_AVAILABLE,
      lightingLevel: LightingLevel.DIM,
      crowdLevel: CrowdLevel.CROWDED,
      peakHours: '07:00 - 09:00, 16:30 - 19:30',
      safeVisitTime: '08:00 - 16:00',
      weeklyPattern: WeeklyPattern.WEEKDAY_BUSY,
      overallScore: 2.2,
      physicalScore: 2.0,
      safetyScore: 2.4,
      aiSummary: 'Trotoar membutuhkan perhatian dan perbaikan mendesak. Permukaan berlubang, undakan tinggi tanpa ramp, dan guiding block terputus oleh tiang utilitas serta parkir kendaraan.',
      aiInsights: {
        strengths: ['Berada di koridor padat rute angkutan umum'],
        barriers: ['Trotoar berlubang', 'Guiding block terputus parah', 'Tidak ada ramp penyeberangan'],
        keyPoints: ['Prioritas Tinggi Revitalisasi', 'Trotoar Rusak', 'Bahaya Pengguna Kursi Roda'],
      },
      economicScore: 94.0,
      priorityIndex: 86.5,
    },
  ];

  for (const loc of locationsData) {
    await prisma.location.upsert({
      where: { id: loc.id },
      update: loc,
      create: loc,
    });
    console.log(`📍 Seeded Location: ${loc.name} (${loc.entityType} - Score: ${loc.overallScore})`);
  }

  // 3. Seed Sample Activities (Community Postings with Photos)
  const activitiesData = [
    {
      id: 'aaaa1111-1111-1111-1111-111111111111',
      userId: demoUser.id,
      locationId: '66666666-6666-6666-6666-666666666666', // Danau UNHAS
      title: 'Danau UNHAS - Mampir lihat Danau Unhas',
      description: 'Pemandangan sore di danau sangat tenang. Jalur keliling danau cukup rata untuk kursi roda manual, tapi hati-hati di sisi timur karena lampu jalan belum semuanya menyala.',
      mediaUrls: [
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
        'https://images.unsplash.com/photo-1439853941329-a99ce0457e8a?w=800',
      ],
      specificLocation: 'Danau UNHAS Tamalanrea',
      latitude: -5.13842,
      longitude: 119.49214,
      status: ActivityStatus.PUBLIC,
      accessibilityTags: ['Kursi Roda', 'Danau', 'Jalur Datar'],
      aiScore: 4.0,
      aiAnalysis: {
        summary: 'Kondisi jalur danau ramah kursi roda dengan permukaan semen rata.',
        barrierType: 'Pencahayaan malam minim',
        actionRecommendation: 'Penambahan lampu taman dan ubin pemandu di jalur utama.',
        physicalScore: 4.2,
        safetyScore: 3.8,
      },
      observedParameters: {
        rampStatus: RampStatus.GOOD,
        guidingBlockStatus: GuidingBlockStatus.NONE,
        surfaceCondition: SurfaceCondition.SMOOTH,
        lightingLevel: LightingLevel.DIM,
        crowdLevel: CrowdLevel.MODERATE,
      },
    },
    {
      id: 'bbbb2222-2222-2222-2222-222222222222',
      userId: demoUser.id,
      locationId: '11111111-1111-1111-1111-111111111111', // MaRI
      title: 'Aksesibilitas Kursi Roda Pintu Utara MaRI',
      description: 'Ramp masuk di lobby utara sangat landai dan nyaman. Satpam sigap membantu membukakan pintu ramah disabilitas.',
      mediaUrls: [
        'https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=800',
      ],
      specificLocation: 'Mal Ratu Indah',
      latitude: -5.15832,
      longitude: 119.41654,
      status: ActivityStatus.PUBLIC,
      accessibilityTags: ['Kursi Roda', 'Ramp Landai', 'Pelayanan Ramah'],
      aiScore: 4.9,
      aiAnalysis: {
        summary: 'Fasilitas ramp lobby utara memenuhi standar aksesibilitas nasional.',
        barrierType: 'Tidak ada hambatan',
        actionRecommendation: 'Pertahankan kualitas fasilitas dan kesiagaan petugas.',
        physicalScore: 5.0,
        safetyScore: 4.8,
      },
      observedParameters: {
        rampStatus: RampStatus.GOOD,
        guidingBlockStatus: GuidingBlockStatus.GOOD,
        surfaceCondition: SurfaceCondition.SMOOTH,
        lightingLevel: LightingLevel.BRIGHT,
        crowdLevel: CrowdLevel.MODERATE,
      },
    },
    {
      id: 'cccc3333-3333-3333-3333-333333333333',
      userId: demoUser.id,
      locationId: '88888888-8888-8888-8888-888888888888', // Trotoar Perintis
      title: 'Guiding Block Terputus di Trotoar Perintis KM 10',
      description: 'Ubin pemandu tunanetra terputus akibat ada tiang listrik di tengah trotoar dan paving amblas. Sangat berbahaya bagi tunanetra yang berjalan tanpa pendamping.',
      mediaUrls: [
        'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
      ],
      specificLocation: 'Trotoar Jl. Perintis Kemerdekaan KM 10',
      latitude: -5.13612,
      longitude: 119.48931,
      status: ActivityStatus.PUBLIC,
      accessibilityTags: ['Bahaya Tunanetra', 'Trotoar Rusak', 'Guiding Block Terputus'],
      aiScore: 2.0,
      aiAnalysis: {
        summary: 'Rintangan fisik permanen di jalur pedestrian yang memutus rute mandiri disabilitas sensorik.',
        barrierType: 'Tiang di jalur taktil & paving amblas',
        actionRecommendation: 'Dinas PU perlu merelokasi jalur ubin taktil memutar dari tiang utilitas.',
        physicalScore: 1.8,
        safetyScore: 2.2,
      },
      observedParameters: {
        rampStatus: RampStatus.NONE,
        guidingBlockStatus: GuidingBlockStatus.DAMAGED,
        sidewalkCondition: SidewalkCondition.DAMAGED,
        surfaceCondition: SurfaceCondition.POTHOLE,
        lightingLevel: LightingLevel.DIM,
        crowdLevel: CrowdLevel.CROWDED,
      },
    },
  ];

  for (const act of activitiesData) {
    await prisma.activity.upsert({
      where: { id: act.id },
      update: act,
      create: act,
    });
    console.log(`📸 Seeded Activity: ${act.title}`);
  }

  // 4. Update Activity Counter di Location
  await prisma.location.update({
    where: { id: '66666666-6666-6666-6666-666666666666' },
    data: { totalActivities: 1 },
  });
  await prisma.location.update({
    where: { id: '11111111-1111-1111-1111-111111111111' },
    data: { totalActivities: 1 },
  });
  await prisma.location.update({
    where: { id: '88888888-8888-8888-8888-888888888888' },
    data: { totalActivities: 1 },
  });

  console.log('✅ Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
